# Generated by Django 4.0.5 on 2022-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
