# Generated by Django 4.0.5 on 2022-06-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_family_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
