# Generated by Django 4.0.5 on 2022-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_alter_family_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
