# Generated by Django 4.0.5 on 2022-06-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_child_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='chore_state',
        ),
    ]
