# Generated by Django 4.0.5 on 2022-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_remove_task_chore_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points_value',
            field=models.FloatField(),
        ),
    ]
