# Generated by Django 4.0.5 on 2022-06-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name=[(1, 'Done'), (2, 'Not Done'), (3, 'Void')])),
                ('points', models.FloatField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.child')),
                ('chore', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chores.task')),
            ],
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
