# Generated by Django 4.0.5 on 2022-06-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_chorelog_delete_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('action_type', models.IntegerField(choices=[(1, 'Chore'), (2, 'Spend')])),
                ('points', models.FloatField(default=0.0)),
                ('state', models.IntegerField(default=3, verbose_name=[(1, 'Done'), (2, 'Not Done'), (3, 'Void')])),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.child')),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chores.task')),
            ],
        ),
        migrations.DeleteModel(
            name='ChoreLog',
        ),
    ]
