# Generated by Django 4.0.5 on 2022-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_accoutlog_delete_chorelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accoutlog',
            name='state',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name=[(1, 'Done'), (2, 'Not Done'), (3, 'Void')]),
        ),
    ]
